// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMANFxAzMWCOWglxWJFCRVPOQlKVjky3Y',
    appId: '1:847357302431:web:e9b2ec818abc4970ec34aa',
    messagingSenderId: '847357302431',
    projectId: 'pruebatech-a089d',
    authDomain: 'pruebatech-a089d.firebaseapp.com',
    storageBucket: 'pruebatech-a089d.firebasestorage.app',
    measurementId: 'G-F3STNSQ7B4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qyFXrX5KpB5OizV-_2ekQa5WBmhr6sc',
    appId: '1:847357302431:ios:c8df8ca8296c7d0bec34aa',
    messagingSenderId: '847357302431',
    projectId: 'pruebatech-a089d',
    storageBucket: 'pruebatech-a089d.firebasestorage.app',
    iosClientId: '847357302431-00sl23cos6300bmhgj8a7fbo1l3ohr1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMANFxAzMWCOWglxWJFCRVPOQlKVjky3Y',
    appId: '1:847357302431:web:970fae366a3d7deaec34aa',
    messagingSenderId: '847357302431',
    projectId: 'pruebatech-a089d',
    authDomain: 'pruebatech-a089d.firebaseapp.com',
    storageBucket: 'pruebatech-a089d.firebasestorage.app',
    measurementId: 'G-MZGPLPEPSG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qyFXrX5KpB5OizV-_2ekQa5WBmhr6sc',
    appId: '1:847357302431:ios:c8df8ca8296c7d0bec34aa',
    messagingSenderId: '847357302431',
    projectId: 'pruebatech-a089d',
    storageBucket: 'pruebatech-a089d.firebasestorage.app',
    iosClientId: '847357302431-00sl23cos6300bmhgj8a7fbo1l3ohr1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalTest',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzptWybO6KhaIIlkA3dpCE4HO1xeh7Z4',
    appId: '1:847357302431:android:8911a344a7fde207ec34aa',
    messagingSenderId: '847357302431',
    projectId: 'pruebatech-a089d',
    storageBucket: 'pruebatech-a089d.firebasestorage.app',
  );

}